### ISSUE TITLE
[SMOKE TEST]: v2408 Gated OS Testing

### ISSUE THREAD

**Issue by gus33000** [WOA-Project/SurfaceDuo-Drivers#24]
Goal is to validate the upcoming release and catch issues ahead of time before release. Below is the list of "must be compatible" targets for 2408, a tick means testing passed:

- Surface Duo (1st Gen)
  - [ ] RS4 Client
  - [ ] Calcium Client
  - [ ] Titanium/Vanadium Client
  - [x] Vibranium Client
  - [ ] Manganese Client
  - [ ] Iron Client
  - [ ] Iron Server
  - [ ] Iron WCOS
  - [x] Cobalt Client
  - [ ] Cobalt WCOS
  - [ ] Nickel Client
  - [x] Germanium Client

- Surface Duo 2
  - [ ] Germanium Client

**Comment by gus33000** [comment]
NB: 18262.1 Titanium Semester builds do not boot at all on GICv3 hardware due to a bug, a Cumulative Update is required to address this issue, .1 is a "cant fix" scenario in above matrix.

**Comment by Marcinoo97** [comment]
18362?

**Comment by gus33000** [comment]
Failures observed on NI/CO/etc: #25 #26

**Comment by gus33000** [comment]
Ok release for this week is halted

#27

This must get fixed, improper battery management could potentially result in >1A current going through the hinge connection wires which is way above spec and would damage them if thats the reason for the fail trigger.

Will revist testing once fixed

**Comment by gus33000** [comment]
Driver Load order issue found on VB_RELEASE triggering BlackScreen issue on first boot due to clash between SLPI Hall sensor initialization (for hinge angle and posture sensor algos) as well as lid functionality in the OS.

Such issue does not happen on GE_RELEASE and CO_RELEASE so far with privately available firmware patch of 7/26

**Comment by gus33000** [comment]
Zeta is non functional on GE_RELEASE due to two key issues:

- Hypervisor fault upon loading ADSP node in HLOS
- IRQ storm on PEP device for either PCIe, TSENS, CPUSS or RDM after a few mins

**Comment by gus33000** [comment]
=> release delayed again
