### ISSUE TITLE
Does Domain Join and Direct Access work?

### ISSUE THREAD

**Issue by thenewguy** [WOA-Project/SurfaceDuo-Drivers#6]
I just stumbled upon this project. Can one join a domain and make use of Direct Access on the duo phone with this?

**Comment by gus33000** [comment]
Hi!

Yes these should work as they are windows pro features after all. Though if your organization enforces some security features you should be aware as of right now secureboot has to remain disabled (because drivers aren't whql) and there isn't any hypervisor based security.

**Comment by thenewguy** [comment]
Which phone would you recommend to use for a first try?
