### ISSUE TITLE
 GPU driver only supports OpenGL 1.1

### ISSUE THREAD

**Issue by anseyuyin** [WOA-Project/SurfaceDuo-Drivers#8]
If can support OpenGL 2.1 or above, it will be very helpful.

**Comment by Marcinoo97** [comment]
for Qualcomm devices that only support DX12 (OpenGL 1.1 is software rendered and included in OS not driver) the best options is using this combability layer from Microsoft Store  https://apps.microsoft.com/store/detail/opencl%E2%84%A2-and-opengl%C2%AE-compatibility-pack/9NQPSL29BFFF

**Comment by gus33000** [comment]
Correct, no qualcomm gpu driver for windows support anything but DIrectX natively, for anything else you want a translation layer. This is out of scope for this project unfortunately. Sorry.
